name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Unzip project
        run: |
          unzip find_my_cni_expo.zip -d app-source
          mv app-source/* .
          rm -rf app-source find_my_cni_expo.zip
          
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPOTOKEN }}
          
      - name: Install dependencies
        run: npm install
        
      - name: Build Android
        run: eas build -p android --profile production --non-interactive --auto-submit=false
